language: node_js
node_js:
  - 14
  - 15

services:
  - docker

before_install:
  - npm install -g gulp-cli
  - docker-compose build

install:
  - npm install gulp-run
  - gulp install

before_script:
  - docker-compose up -d

script:
  - gulp test
  - curl --location --request GET 'http://localhost:6001/libros/'
  - curl --location --request GET 'http://localhost:6002/prestamos/'
  - curl --location --request GET 'http://localhost:6003/usuarios/'