language: node_js
node_js:
  - 12
  - 14
  - 15

services:
  - docker

before_install:
  - npm install -g gulp-cli
  - docker-compose build

install:
  - npm install gulp-run
  - gulp install

script:
  - gulp test
  - docker-compose up -d
  - curl -sL -w "http://localhost:6001/libros"
  - curl -sL -w "http://localhost:6002/usuarios"
  - curl -sL -w "http://localhost:6003/prestamos"