environment:
  matrix:
    - nodejs_version: '16'
    - nodejs_version: '10'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g glup-cli gulp-run
  - gulp install
build: off
test_script:
  - gulp test