version: '3'
# Declaramos los tres servicios
services:
  # Microservicio de libros
  libros:
    # Nombre del contenedor
    container_name: libros 
    # Ubicación del Dockerfile. En "context" indicamos el directorio y en "dockerfile" el nombre del mismo
    build: 
      context: .
      dockerfile: libros.Dockerfile
    # Abrimos los puertos
    ports:
         - "6001:6001"
    # Red para comunicación entre microservicios
    networks: 
      - bliotecNetwork

  # Microservicio de préstamos
  prestamos:
    container_name: prestamos
    build: 
      context: .
      dockerfile: prestamos.Dockerfile
    ports:
         - "6002:6002"
    networks: 
      - bliotecNetwork

  # Microservicio de usuarios
  usuarios:
    container_name: usuarios
    build: 
      context: .
      dockerfile: usuarios.Dockerfile
    ports:
         - "6003:6003"
    networks: 
      - bliotecNetwork

# Creación de la red de comunicación
networks:
  bliotecNetwork:
    #Todos los contenedores en una misma red
    driver: bridge


