version: 2.1
jobs:
  test:
    docker:
      - image: fer227/bliotec:latest
    steps:
      - checkout
      - run: cp -R /app/test/node_modules ./node_modules
      - run: cd /app/test
      - run: ls -la
      - run: pwd
      - run: gulp test
workflows:
  tests:
    jobs:
      - test